# Development environment overrides
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

version: '3.8'

services:
  app:
    build:
      target: development
    environment:
      - GO_ENV=development
      - SWAGGER_ENABLED=true
      - LOG_LEVEL=debug
    volumes:
      - .:/app/src:cached # Mount source code for hot reload
      - /app/src/bin # Exclude bin directory
      - /app/src/docs # Exclude docs directory
    command: >
      sh -c "
        echo 'Starting development server...'
        echo 'Swagger UI: http://localhost:8080/swagger/index.html'
        go run cmd/server/main.go
      "
    ports:
      - "8080:8080"
      - "2345:2345" # Delve debugger port

  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=dev_password
      - MYSQL_DATABASE=go_micro_scaffold_dev
    ports:
      - "3306:3306"

  redis:
    environment:
      - REDIS_PASSWORD=
    ports:
      - "6379:6379"

  # Development tools
  adminer:
    image: adminer:latest
    container_name: go-micro-scaffold-adminer
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    depends_on:
      - mysql
    networks:
      - app-network
    profiles:
      - dev-tools

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: go-micro-scaffold-redis-commander
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - app-network
    profiles:
      - dev-tools
