# Production environment overrides
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

version: '3.8'

services:
  app:
    environment:
      - GO_ENV=production
      - SWAGGER_ENABLED=false # Disabled for security in production
      - LOG_LEVEL=warn
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "8080" # Let Docker assign random ports for load balancing

  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=${PROD_DB_PASSWORD}
      - MYSQL_DATABASE=go_micro_scaffold_prod
    volumes:
      - mysql_prod_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '1.0'
          memory: 512M

  redis:
    environment:
      - REDIS_PASSWORD=${PROD_REDIS_PASSWORD}
    volumes:
      - redis_prod_data:/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  # Enable nginx and monitoring for production
  nginx:
    profiles: [] # Remove profile to enable by default
    volumes:
      - ./configs/nginx/production.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro # SSL certificates
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M

  prometheus:
    profiles: [] # Enable monitoring in production

  grafana:
    profiles: [] # Enable monitoring in production

  # Log aggregation
  fluentd:
    image: fluent/fluentd:v1.16-debian-1
    container_name: go-micro-scaffold-fluentd
    volumes:
      - ./configs/fluentd:/fluentd/etc:ro
      - ./logs:/var/log/app:ro
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

volumes:
  mysql_prod_data:
    driver: local
  redis_prod_data:
    driver: local
