# Staging environment overrides
# Usage: docker-compose -f docker-compose.yml -f docker-compose.staging.yml up

version: '3.8'

services:
  app:
    environment:
      - GO_ENV=staging
      - SWAGGER_ENABLED=true
      - LOG_LEVEL=info
    ports:
      - "8080:8080"

  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=${STAGING_DB_PASSWORD}
      - MYSQL_DATABASE=go_micro_scaffold_staging
    volumes:
      - mysql_staging_data:/var/lib/mysql

  redis:
    environment:
      - REDIS_PASSWORD=${STAGING_REDIS_PASSWORD}
    volumes:
      - redis_staging_data:/data

  # Enable nginx for staging
  nginx:
    profiles: [] # Remove profile to enable by default
    volumes:
      - ./configs/nginx/staging.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mysql_staging_data:
    driver: local
  redis_staging_data:
    driver: local
