# Development Environment Configuration
# This file contains development-specific settings with Swagger enabled

server:
  port: 8080
  mode: "debug"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

# Swagger configuration for development
swagger:
  enabled: true
  title: "Go Micro Scaffold API (Development)"
  description: "微服务脚手架 API 文档 - 开发环境"
  version: "1.0.0-dev"
  host: "localhost:8080"
  base_path: "/api/v1"
  schemes: ["http"]
  contact:
    name: "Development Team"
    email: "dev@example.com"
    url: "https://github.com/your-org/go-micro-scaffold"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"

# Database configuration
database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  name: "go_micro_scaffold_dev"
  user: "root"
  password: "dev_password"
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: 300s
  charset: "utf8mb4"
  parse_time: true
  loc: "Asia/Shanghai"

# Redis configuration
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  pool_timeout: 4s
  idle_timeout: 300s

# JWT configuration
jwt:
  secret: "dev-secret-key-change-in-production"
  expired_time: 60  # minutes
  refresh_expired_time: 1440  # minutes (24 hours)
  issuer: "go-micro-scaffold-dev"

# Logging configuration
logging:
  level: "debug"
  format: "console"  # console or json
  output: ["stdout", "file"]
  file_path: "logs/app.log"
  max_size: 100  # MB
  max_backups: 7
  max_age: 30  # days
  compress: true

# System configuration
system:
  timezone: "Asia/Shanghai"
  secret_key: "dev-system-secret-key-32-characters"
  debug: true
  
# CORS configuration
cors:
  allow_origins: ["*"]
  allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allow_headers: ["*"]
  expose_headers: ["Content-Length"]
  allow_credentials: true
  max_age: 12h

# Rate limiting
rate_limit:
  enabled: false  # Disabled in development for easier testing
  requests_per_minute: 1000
  burst: 100

# Middleware configuration
middleware:
  request_logger:
    enabled: true
    skip_paths: ["/health", "/ping", "/swagger"]
  
  recovery:
    enabled: true
    stack_trace: true
  
  auth:
    skip_paths: ["/health", "/ping", "/swagger", "/api/v1/auth/login"]
  
  ip_access_control:
    enabled: false  # Disabled in development
    whitelist: []
    blacklist: []

# Monitoring and metrics
monitoring:
  enabled: true
  prometheus:
    enabled: true
    path: "/metrics"
  
  health_check:
    enabled: true
    path: "/health"
  
  pprof:
    enabled: true  # Enabled for development debugging
    path: "/debug/pprof"

# External services
external_services:
  timeout: 30s
  retry_attempts: 3
  retry_delay: 1s