# Staging Environment Configuration
# This file contains staging-specific settings with Swagger enabled but with authentication

server:
  port: 8080
  mode: "release"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

# Swagger configuration for staging
swagger:
  enabled: true
  title: "Go Micro Scaffold API (Staging)"
  description: "微服务脚手架 API 文档 - 预发布环境"
  version: "1.0.0-staging"
  host: "staging-api.example.com"
  base_path: "/api/v1"
  schemes: ["https", "http"]
  contact:
    name: "API Support"
    email: "support@example.com"
    url: "https://github.com/your-org/go-micro-scaffold"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"

# Database configuration
database:
  driver: "mysql"
  host: "${DB_HOST}"
  port: 3306
  name: "${DB_NAME}"
  user: "${DB_USER}"
  password: "${DB_PASSWORD}"
  max_open_conns: 25
  max_idle_conns: 10
  conn_max_lifetime: 300s
  charset: "utf8mb4"
  parse_time: true
  loc: "Asia/Shanghai"

# Redis configuration
redis:
  host: "${REDIS_HOST}"
  port: 6379
  password: "${REDIS_PASSWORD}"
  db: 0
  pool_size: 20
  min_idle_conns: 10
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  pool_timeout: 4s
  idle_timeout: 300s

# JWT configuration
jwt:
  secret: "${JWT_SECRET}"
  expired_time: 30  # minutes
  refresh_expired_time: 720  # minutes (12 hours)
  issuer: "go-micro-scaffold-staging"

# Logging configuration
logging:
  level: "info"
  format: "json"
  output: ["stdout", "file"]
  file_path: "logs/app.log"
  max_size: 100  # MB
  max_backups: 14
  max_age: 30  # days
  compress: true

# System configuration
system:
  timezone: "Asia/Shanghai"
  secret_key: "${SYSTEM_SECRET_KEY}"
  debug: false
  
# CORS configuration
cors:
  allow_origins: ["https://staging-web.example.com", "https://staging-admin.example.com"]
  allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allow_headers: ["Content-Type", "Authorization", "X-Requested-With"]
  expose_headers: ["Content-Length"]
  allow_credentials: true
  max_age: 12h

# Rate limiting
rate_limit:
  enabled: true
  requests_per_minute: 300
  burst: 50

# Middleware configuration
middleware:
  request_logger:
    enabled: true
    skip_paths: ["/health", "/ping"]
  
  recovery:
    enabled: true
    stack_trace: false
  
  auth:
    skip_paths: ["/health", "/ping", "/api/v1/auth/login"]
  
  ip_access_control:
    enabled: true
    whitelist: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
    blacklist: []

# Monitoring and metrics
monitoring:
  enabled: true
  prometheus:
    enabled: true
    path: "/metrics"
  
  health_check:
    enabled: true
    path: "/health"
  
  pprof:
    enabled: false  # Disabled in staging for security

# External services
external_services:
  timeout: 30s
  retry_attempts: 3
  retry_delay: 2s

# Security settings
security:
  tls:
    enabled: true
    cert_file: "/etc/ssl/certs/staging.crt"
    key_file: "/etc/ssl/private/staging.key"
  
  headers:
    x_frame_options: "DENY"
    x_content_type_options: "nosniff"
    x_xss_protection: "1; mode=block"
    strict_transport_security: "max-age=31536000; includeSubDomains"