system:
  env: "development"
  port: "8080"
  secret_key: "cloud-motion-secret-key"
  server_name: "services"

token:
  expired_time: 30 # 分钟

snow_flake:
  start_time: "2024-01-01"
  machine_id: 1

database:
  type: "mysql"
  host: "127.0.0.1"
  port: 3306
  database: go-micro-scaffold
  username: root
  password: ""
  charset: utf8mb4
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 1h
  conn_max_idle_time: 30m
  log_level: 1

# # 多数据源  
# databases:
#   # 主数据库
#   primary:
#     type: "mysql"
#     host: "127.0.0.1"
#     port: 3306
#     database: "go-micro-scaffold"
#     username: "root"
#     password: ""
#     charset: "utf8mb4"
#     parse_time: true
#     loc: "Local"
#     max_idle_conns: 10
#     max_open_conns: 100
#     conn_max_lifetime: 3600
    
#   # 分析数据库 - 统计分析、报表数据
#   analytics:
#     type: "mysql"
#     host: "127.0.0.1"
#     port: 3306
#     database: "go-micro-scaffold"
#     username: "root"
#     password: ""
#     charset: "utf8mb4"
#     parse_time: true
#     loc: "Local"
#     max_idle_conns: 5
#     max_open_conns: 50
#     conn_max_lifetime: 3600

redis:
  prefix: "cloud_motion"
  host: "127.0.0.1"
  port: 6379
  password: ""
  database: 0
  default_db: 0
  pool_size: 10

server:
  port: "8080"
  mode: debug

zap:
  level: "DEBUG"
  director: "./logs"
  max_age: 30
  max_size: 500
  max_backups: 7

wechat:
  app_id_mini: ""
  secret_mini: ""
  app_id_serve: ""
  secret_serve: ""
  team_status_message_id: ""
  payment_notice_message_id: ""
  merch_id: ""
  payment_notify_url: ""
  refund_notify_url: ""
  get_openid_url: "https://api.weixin.qq.com/sns/jscode2session"
  get_access_token_url: "https://api.weixin.qq.com/cgi-bin/token"
  get_phone_number_url: "https://api.weixin.qq.com/wxa/business/getuserphonenumber"
  send_template_message_url: "https://api.weixin.qq.com/cgi-bin/message/subscribe/send"

aliyun_sms:
  access_key_id: ""
  access_key_secret: ""
  region_id: "cn-hangzhou"
  endpoint: "dysmsapi.aliyuncs.com"
  sign_name: ""
  team_notice_code: ""
  payment_notice_code: ""

validation:
  locale: "zh"